POST http://localhost:9010/api/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg2NTUwMjQ2LCJwaG9uZSI6OTExfQ.E8p6UCwnsEsI2Ohloe_sn5Ckr4ebOxDY7EZ09e3naYc
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "Transfer_money",
  "number": "202160000000001",
  "recipientsender": "sender",
  "count": 10,
  "balanceold": 33,
  "balancenew": 23,
  "time": 1584689800,
  "ownerid": 2
}


###
# No Admin list history
GET http://localhost:9010/api/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzA5MDUwfQ.IH-UbER3ou6Hm1ECBwxDpmweLyOP7vBumFjrmoFMMw8

###
# Has Admin list history
GET http://localhost:9010/api/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MTg3MTk0LCJwaG9uZSI6OTExfQ.qiNnruVjbod9lP5g4_33kaWPpGCf2OHMBwwl6--Jt3g

###
#
GET http://localhost:9009/api/cards/ownerid/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwicm9sZXMiOm51bGwsImV4cCI6MTU4NDY2MzMzMX0.UltpIFXFw_j8XU-0XYIu3fSkgCKvXOTL7_IyW5rXr4s
###

GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTg3MTg2NTM3LCJwaG9uZSI6OTExfQ.xewl5n66Wm35ba8FzXSPmQGTGqp4C2vfJhIvLjIFg34

###

GET http://localhost:9009/api/cards/ownerid/1

###


POST http://localhost:9009/api/cards/transmoney/0
Content-Type: application/json
Accept: application/json

{
  "IdCardSender": 0,
  "NumberCardRecipient": "202160000000009",
  "Count": 150
}

###