POST http://localhost:9010/api/history/0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0NzA5MDUwfQ.5N3oREIhPW6gPo30GzStAGTus_F2nYQfBFzxi8zNX8I
Content-Type: application/json
Accept: application/json

{
  "Name": "Transfer money",
  "Number": "202160000000001",
  "RecipientSender": "sender",
  "Count": 150,
  "BalanceOld": 200,
  "BalanceNew": 50,
  "Time": 1584689646,
  "OwnerID": 1
}


###
# No Admin list history
GET http://localhost:9010/api/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwiZXhwIjoxNTg0NzA5MDUwfQ.IH-UbER3ou6Hm1ECBwxDpmweLyOP7vBumFjrmoFMMw8

###
# Has Admin list history
GET http://localhost:9010/api/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0NzA5MDUwfQ.5N3oREIhPW6gPo30GzStAGTus_F2nYQfBFzxi8zNX8I

###
#
GET http://localhost:9009/api/cards/ownerid/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlZhc3lhIiwicm9sZXMiOm51bGwsImV4cCI6MTU4NDY2MzMzMX0.UltpIFXFw_j8XU-0XYIu3fSkgCKvXOTL7_IyW5rXr4s
###

GET http://localhost:9009/api/cards
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IlBldHlhIiwiZXhwIjoxNTg0Njg1NDAzfQ.-72pg0Axdjf06ayPxSzlGc6P_ZpV0xTDwdG3O2vDX6E

###

GET http://localhost:9009/api/cards/ownerid/1

###


POST http://localhost:9009/api/cards/transmoney/0
Content-Type: application/json
Accept: application/json

{
  "IdCardSender": 0,
  "NumberCardRecipient": "202160000000009",
  "Count": 150
}

###